### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by DD4WH** [mcguirepr89/BirdNET-Lite#5]
maybe we should consider adding multithreading in order to speed up BirdNET-Lite analysis. This does not seem to be relevant for the use of birdnet-system as a realtime device (because there is enough time while the RPi is recording), but should be extremely relevant when using birdnetsystem to analyse a large batch of recordings (made with other recorders etc.).

* change line 27 of analyze.py to `interpreter = tflite.Interpreter(model_path='model/BirdNET_6K_GLOBAL_MODEL.tflite', num_threads=2)`
* this achieved a 30% reduction of analysis time on my RPi
* increasing num_threads to 3 did reduce analysis time further, but only a few%

**Comment by mcguirepr89** [comment]
That's added now to the rpi4 branch -- thank you!
